# Import the repository signing key:
# wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

- name: 'Install GPG key for apt.postgresql.org'
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present

# Create the file repository configuration:
# sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

- name: 'Generate /etc/apt/sources.list.d/pgdg.list'
  template:
    src: 'etc/apt/sources.list.d/pgdg.list.j2'
    dest: '/etc/apt/sources.list.d/pgdg.list'

# sudo apt-get update
# sudo apt-get -y install postgresql-14

- name: "Install PostgreSQL {{ postgres_version }}"
  apt:
    name: "postgresql-{{ postgres_version }}"
    state: present
    update_cache: yes

# sudo apt-get -y install postgresql-13-postgis-3

- name: "Install PostGIS {{ postgres_postgis_version }}"
  apt:
    name: "postgresql-{{ postgres_version }}-postgis-{{ postgres_postgis_version }}"
    state: present
    update_cache: yes
  when: postgres_postgis_enabled | bool

- name: Configure listen_addresses to '*' in postgresql.conf
  lineinfile:
    dest: /etc/postgresql/{{ postgres_version }}/main/postgresql.conf
    regexp: "listen_addresses ="
    line: "listen_addresses = '*'"
    state: present
  notify: restart postgresql

