version: '3.5'

services:

  postgis:
    container_name: geostack_postgis
    image: postgis/postgis:13-3.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgis-data:/var/lib/postgresql/data
    restart: unless-stopped

  geoserver:
    container_name: geostack_geoserver
    image: ghcr.io/mborne/geoserver:v2.21.1
    ports:
      - "8082:8080"
    volumes:
      - geoserver-data:/var/geoserver-data-dir
    restart: unless-stopped

volumes:
  postgis-data:
    name: geostack-postgis-data
  geoserver-data:
    name: geostack-geoserver-data

networks:
  geostack:

